---
exclude: build-support/alpha-build/core|build-support/git-bash-integration|docs
repos:
  # Prettier auto-formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      # On Windows, this writes \r\n newlines that need to be fixed by the next hook
      - id: prettier
  # GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: check-ast
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  # Python auto-formatters
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
  #  - repo: https://github.com/asottile/yesqa
  #    rev: v1.4.0
  #    hooks:
  #      - id: yesqa
  #        additional_dependencies:
  #          - wemake-python-styleguide
  #          - flake8-annotations
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries=120
          - --wrap-descriptions=120
  - repo: https://github.com/ikamensh/flynt
    rev: '0.76'
    hooks:
      - id: flynt
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]
  # Black also applies to notebooks
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  # Python linters
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - wemake-python-styleguide
          - flake8-annotations
        exclude: README.md
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        name: bandit
        args: [--configfile pyproject.toml]
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml]
  # JUPYTER auto-formatters
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  # BASH auto-formatters
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args: [-i=4]
  # BASH linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: [-x]
  # YAML linters
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yml]
  # NOTE! Direct usage of flake8 is disabled (uncomment to use flake8 specifically)
  #       flake8 is used via flakeheaven which is preferred because it allows running flake8 with plugins on legacy code
  #  - repo: https://github.com/pycqa/flake8
  #    rev: ''
  #    hooks:
  #      - id: flake8
  # NOTE! Usafe of mypy from the mirror is disabled, prefer the local installation of mypy such that one could have
  #       access to all the type annotations exported by third party libraries.
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: ''
  #    hooks:
  #      - id: mypy
  #        additional_dependencies:
  #          - sqlalchemy[mypy]
  #          - pydantic
